version: "3.7"

services:
    node:
        image: aiccuracy/node
        links: 
            - mongodb
        restart: always
        container_name: node
        ports:
            - "8001:8001"
        depends_on:
            - mongodb
        build:
            dockerfile: Dockerfile
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"