version: "3.7"

services:
    node:
        image: aiccuracy/node
        container_name: node
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "3000:3000"
        restart: always
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        restart: always
